export const SHOW_PRODUCT = 'SHOW_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_SIZE = 'CHANGE_SIZE';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const START_APP = 'START_APP';
export const START_LOGIN = 'START_LOGIN';
export const PAYMENT_CART = 'PAYMENT_CART';
export const REMOVE_CARTS = "REMOVE_CARTS";

// type of redux-saga
export const FETCH_SUCCESS_PRODUCTS = 'FETCH_SUCCESS_PRODUCTS';
export const FETCH_FAIL_PRODUCTS = 'FETCH_FAIL_PRODUCTS';
export const GET_SUCCESS_CARTS_ASYNCSTORAGE = 'GET_SUCCESS_CARTS_ASYNCSTORAGE';
export const GET_FAIL_CARTS_ASYNCSTORAGE = 'GET_FAIL_CARTS_ASYNCSTORAGE';
export const REMOVE_SUCCESS_CARTS_ASYNCSTORAGE = 'REMOVE_SUCCESS_CARTS_ASYNCSTORAGE';
export const FEETCH_SUCCESS_LOGIN = 'FEETCH_SUCCESS_LOGIN';
export const FEETCH_FAILD_LOGIN = 'FEETCH_FAILD_LOGIN';