export const SHOW_PRODUCT = 'SHOW_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_SIZE = 'CHANGE_SIZE';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const START_APP = 'START_APP';

// type of redux-saga
export const FETCH_SUCCESS_PRODUCTS = 'FETCH_SUCCESS_PRODUCTS';
export const FETCH_FAIL_PRODUCTS = 'FETCH_FAIL_PRODUCTS';
export const GET_SUCCESS_CARTS_ASYNCSTORAGE = 'GET_SUCCESS_CARTS_ASYNCSTORAGE';
export const GET_FAIL_CARTS_ASYNCSTORAGE = 'GET_FAIL_CARTS_ASYNCSTORAGE';
